name: uisng the ansible playbook 

on:
  workflow_dispatch:
    inputs:
      ansible-version:
        required: true 
        type: string
        default: "2.9.2"

jobs:
   dummy-ansible:
      runs-on: ubuntu-latest
      steps:
      - name: using checkout action 
        uses: actions/checkout@v6.0.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  

      - name: steup the ansible 
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: ${{ inputs.ansible-version }}

      - name: check the ansible version 
        run: ansible --version 

      - name: run the ansible playbook 
        run: ansible-playbook testplaybook.yml
        working-directory: ng-beginner-github-action
       
        
        
      
