name: Build the angular app

on:
  push:
    branches: [ main ]
concurrency:
    cancel-in-progress: false 
    group: ci-${{ github.workflow }}
jobs:
  Running-angular-job:
    uses: ./.github/workflows/reusable.yml
     
