name: using the joboutput 

on:
  push:
    branches: [ main ]

jobs:
   dummy:
     runs-on: ubuntu-latest

     steps:
     - name: using the output 
       id: output_app
       run: echo "app=26 >> $GITHUB_OUTPUT"
       
     - name: print the output of the steps 
       run: echo "${{ steps.output_app.outputs.app }}"

     
    
