name: using the joboutput 

on:
  push:
    branches: [ main ]

jobs:
   dummy:
     runs-on: ubuntu-latest
     outputs:
       job_out: ${{ steps.output_app.outputs.app }}

     steps:
     - name: using the output 
       id: output_app
       run: echo "app=26" >> $GITHUB_OUTPUT
       
     - name: print the output of the steps 
       run: echo "${{ steps.output_app.outputs.app }}"

   reuse-output:
     runs-on: ubuntu-latest
     needs: [ dummy]
     steps:
     - name: using the out from job 1 
       run: echo "${{ needs.dummy.outputs.job_out }}"
         

     
    
