name: using the schedule in the workflow 

on: 
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:  
jobs:
  dummyjob:
    runs-on: ubuntu-latest
    steps:
    - name: using the echo 
      run: |
        echo "This simple job"
        echo "This chceking the schedule"

    - name: Script with workflow commands
      run: |
       echo "MY_VAR=hello" >> $GITHUB_ENV
       echo "::notice::Script executed"     
      

  
  
