name: using the schedule in the workflow 

on: 
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:  
jobs:
  dummyjob:
    runs-on: ubuntu-latest
    steps:
    - name: using the echo 
      run: |
        echo "This simple job"
        echo "This chceking the schedule"
      

  
  
